In [94]:
import numpy as np
import pandas as pd

red=pd.read_csv("C:\\Users\\Asus\\.spyder-py3\\winequality\\winequality-red.csv",sep=";")
white=pd.read_csv("C:\\Users\\Asus\\.spyder-py3\\winequality\\winequality-white.csv",sep=";")

print(red.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5 

In [95]:
red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
size(red)

NameError: name 'size' is not defined

In [4]:
pd.shape(red)

AttributeError: module 'pandas' has no attribute 'shape'

In [6]:
red.shape

(1599, 1)

In [12]:
import numpy as np
import pandas as pd

red=pd.read_csv("C:\\Users\\Asus\\.spyder-py3\\winequality\\winequality-red.csv",sep=";")
white=pd.read_csv("C:\\Users\\Asus\\.spyder-py3\\winequality\\winequality-white.csv",sep=";")


In [13]:
red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [15]:
import numpy as np
import pandas as pd

red_df=pd.read_csv("C:\\Users\\Asus\\.spyder-py3\\winequality\\winequality-red.csv",sep=";")
white_df=pd.read_csv("C:\\Users\\Asus\\.spyder-py3\\winequality\\winequality-white.csv",sep=";")

print(red_df.head())
red_df.rename(columns={"total sulfur dioxide":"total sulfur_dioxide"})
red_df.info()
color_red=np.repeat("red",red_df.shape[0])
red_df["color"]=color_red
print(red_df.head())
print()
print()
wine_df=red_df.append(white_df,sort=False)
print(wine_df.head())
wine_df.to_csv("new_wine.csv",index=False)

wine_df.groupby("color").mean()
               

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5 

fixed acidity  volatile acidity  citric acid  residual sugar  \
color                                                                 
red         8.319637          0.527821     0.270976        2.538806   

       chlorides  free sulfur dioxide  total sulfur dioxide   density  \
color                                                                   
red     0.087467            15.874922             46.467792  0.996747   

             pH  sulphates    alcohol   quality  
color                                            
red    3.311113   0.658149  10.422983  5.636023

# pandas cut function
# quartize fuction using .describe

In [17]:
wine_df.describe()     # this function is important

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378  
std       0.160787     0.148806     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [18]:
#bin edges that will be used to cut the data into groups
bin_edges=[2.72,3.11,3.21,3.32,4.02]

In [20]:
# labels for acidity levels category
bin_names=["high","moderately high","medium","low"]

In [21]:
# Creates acidity levels column
wine_df["acidity_levels"]=pd.cut(wine_df["pH"],bin_edges,labels=bin_names)

In [22]:
#check for creation of labels
wine_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality color   acidity_levels  
0      9.4        5   red              low  
1      9.8        5   red  moderately high  
2      9.8        5   red           medium  
3      9.8        6   red  moderately high  
4      9.4        5   red              low

In [23]:
wine_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00            1.90      0.076   
1               7.8             0.880         0.00            2.60      0.098   
2               7.8             0.760         0.04            2.30      0.092   
3              11.2             0.280         0.56            1.90      0.075   
4               7.4             0.700         0.00            1.90      0.076   
5               7.4             0.660         0.00            1.80      0.075   
6               7.9             0.600         0.06            1.60      0.069   
7               7.3             0.650         0.00            1.20      0.065   
8               7.8             0.580         0.02            2.00      0.073   
9               7.5             0.500         0.36            6.10      0.071   
10              6.7             0.580         0.08            1.80      0.097   
11              7.5             0.500         0.36            6.10      0.071   
12              5.6             0.615         0.00            1.60      0.089   
13              7.8             0.610         0.29            1.60      0.114   
14              8.9             0.620         0.18            3.80      0.176   
15              8.9             0.620         0.19            3.90      0.170   
16              8.5             0.280         0.56            1.80      0.092   
17              8.1             0.560         0.28            1.70      0.368   
18              7.4             0.590         0.08            4.40      0.086   
19              7.9             0.320         0.51            1.80      0.341   
20              8.9             0.220         0.48            1.80      0.077   
21              7.6             0.390         0.31            2.30      0.082   
22              7.9             0.430         0.21            1.60      0.106   
23              8.5             0.490         0.11            2.30      0.084   
24              6.9             0.400         0.14            2.40      0.085   
25              6.3             0.390         0.16            1.40      0.080   
26              7.6             0.410         0.24            1.80      0.080   
27              7.9             0.430         0.21            1.60      0.106   
28              7.1             0.710         0.00            1.90      0.080   
29              7.8             0.645         0.00            2.00      0.082   
...             ...               ...          ...             ...        ...   
4868            5.8             0.230         0.31            4.50      0.046   
4869            6.6             0.240         0.33           10.10      0.032   
4870            6.1             0.320         0.28            6.60      0.021   
4871            5.0             0.200         0.40            1.90      0.015   
4872            6.0             0.420         0.41           12.40      0.032   
4873            5.7             0.210         0.32            1.60      0.030   
4874            5.6             0.200         0.36            2.50      0.048   
4875            7.4             0.220         0.26            1.20      0.035   
4876            6.2             0.380         0.42            2.50      0.038   
4877            5.9             0.540         0.00            0.80      0.032   
4878            6.2             0.530         0.02            0.90      0.035   
4879            6.6             0.340         0.40            8.10      0.046   
4880            6.6             0.340         0.40            8.10      0.046   
4881            5.0             0.235         0.27           11.75      0.030   
4882            5.5             0.320         0.13            1.30      0.037   
4883            4.9             0.470         0.17            1.90      0.035   
4884            6.5             0.330         0.38            8.30      0.048   
4885            6.6             0.340

In [24]:
#find the acidity level of acidity by groupby
wine_df.groupby("acidity_levels").mean()


fixed acidity  volatile acidity  citric acid  residual sugar  \
acidity_levels                                                                  
high                  7.543914          0.294683     0.370792        7.088876   
moderately high       7.365064          0.318551     0.340548        5.931984   
medium                7.143566          0.346751     0.313585        4.721159   
low                   6.769949          0.403815     0.243901        3.848983   

                 chlorides  free sulfur dioxide  total sulfur dioxide  \
acidity_levels                                                          
high              0.055131            33.179965            129.897496   
moderately high   0.054666            33.229154            126.815886   
medium            0.055715            28.983995            111.182138   
low               0.058777            26.327510             93.244917   

                  density        pH  sulphates    alcohol   quality  
acidity_levels                                                       
high             0.994708  3.029062   0.503937  10.330208  5.783343  
moderately high  0.994697  3.164833   0.509300  10.391073  5.784540  
medium           0.994476  3.267010   0.541287  10.610369  5.850832  
low              0.994899  3.433348   0.574136  10.656057  5.859593

In [26]:
#do wines with higher alcoholic content receive better ratings ????
wine_df.describe()



fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378  
std       0.160787     0.148806     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [33]:
low_alcohol=wine_df[wine_df["alcohol"]<10.491801]
high_alcohol=wine_df[wine_df["alcohol"]>=10.491801]

In [37]:
bin_edges=[8,10.3,14.9]
bin_names=["low","high"]
wine_df["alcohol_level"]=pd.cut(wine_df["alcohol"],bin_edges,labels=bin_names)


In [39]:
wine_df.head(50)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4             0.700         0.00             1.9      0.076   
1             7.8             0.880         0.00             2.6      0.098   
2             7.8             0.760         0.04             2.3      0.092   
3            11.2             0.280         0.56             1.9      0.075   
4             7.4             0.700         0.00             1.9      0.076   
5             7.4             0.660         0.00             1.8      0.075   
6             7.9             0.600         0.06             1.6      0.069   
7             7.3             0.650         0.00             1.2      0.065   
8             7.8             0.580         0.02             2.0      0.073   
9             7.5             0.500         0.36             6.1      0.071   
10            6.7             0.580         0.08             1.8      0.097   
11            7.5             0.500         0.36             6.1      0.071   
12            5.6             0.615         0.00             1.6      0.089   
13            7.8             0.610         0.29             1.6      0.114   
14            8.9             0.620         0.18             3.8      0.176   
15            8.9             0.620         0.19             3.9      0.170   
16            8.5             0.280         0.56             1.8      0.092   
17            8.1             0.560         0.28             1.7      0.368   
18            7.4             0.590         0.08             4.4      0.086   
19            7.9             0.320         0.51             1.8      0.341   
20            8.9             0.220         0.48             1.8      0.077   
21            7.6             0.390         0.31             2.3      0.082   
22            7.9             0.430         0.21             1.6      0.106   
23            8.5             0.490         0.11             2.3      0.084   
24            6.9             0.400         0.14             2.4      0.085   
25            6.3             0.390         0.16             1.4      0.080   
26            7.6             0.410         0.24             1.8      0.080   
27            7.9             0.430         0.21             1.6      0.106   
28            7.1             0.710         0.00             1.9      0.080   
29            7.8             0.645         0.00             2.0      0.082   
30            6.7             0.675         0.07             2.4      0.089   
31            6.9             0.685         0.00             2.5      0.105   
32            8.3             0.655         0.12             2.3      0.083   
33            6.9             0.605         0.12            10.7      0.073   
34            5.2             0.320         0.25             1.8      0.103   
35            7.8             0.645         0.00             5.5      0.086   
36            7.8             0.600         0.14             2.4      0.086   
37            8.1             0.380         0.28             2.1      0.066   
38            5.7             1.130         0.09             1.5      0.172   
39            7.3             0.450         0.36             5.9      0.074   
40            7.3             0.450         0.36             5.9      0.074   
41            8.8             0.610         0.30             2.8      0.088   
42            7.5             0.490         0.20             2.6      0.332   
43            8.1             0.660         0.22             2.2      0.069   
44            6.8             0.670         0.02             1.8      0.050   
45            4.6             0.520         0.15             2.1      0.054   
46            7.7             0.935         0.43             2.2      0.114   
47            8.7             0.290         0.52             1.6      0.113   
48            6.4             0.400         0.23             1.6      0.066   
49            5.6             0.310         0.37      

In [41]:
wine_df.groupby("alcohol_level").mean()

fixed acidity  volatile acidity  citric acid  residual sugar  \
alcohol_level                                                                 
low                 7.302217          0.354059     0.315490        6.869329   
high                7.127717          0.324950     0.321927        3.978123   

               chlorides  free sulfur dioxide  total sulfur dioxide   density  \
alcohol_level                                                                   
low             0.064531            33.126177            128.890374  0.996409   
high            0.047307            27.821830            102.198782  0.992935   

                     pH  sulphates    alcohol   quality  
alcohol_level                                            
low            3.203893   0.532602   9.515553  5.485575  
high           3.233423   0.529959  11.497350  6.161774

In [43]:
#question - 01
#Create an empty array of 20 0's and replace the 6th object with the number 5.

#CODING/OUTPUT FORMAT:

#Step 1:- Create an empty array with 20 zeros

#Step 2:- Replace the sixth object with number 5

#Step 3:- Print the array

In [49]:
import numpy as np

x=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
a=np.array(x)
a[6]=5

In [50]:
a

array([0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
x=np.ones(20)
x[:]=100
x

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [55]:
#Create an array of integers starting from 21 until 31 (both included) and name it as array1 and
#create an array of integers starting from 11 until 21 (both included) and name it as array2.
#Calculate the difference between array1 and array2.

In [59]:
x=[21,22,23,24,25,26,27,28,29,30,31]
array1=np.array(x)
y=[11,12,13,14,15,16,17,18,19,20,21]
array2=np.array(y)
array1-array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [60]:
#Create an array of all even integers from 2 to 10 (both included) and 
#name/assign it to a1 and create an array of all even integers from 22 to 30 (both included) and 
#name/assign it to a2 ,Use the 2 arrays as rows(first row as a1, second row as a2) 
#create a matrix [ Hint - Use stack function from numpy ].

In [83]:
x=[]
y=[]

for i in range(2,11):
    if i%2==0:
        x.append(i)

for j in range(22,31):
    if j%2==0:
        y.append(j)
a1=np.array(x)
a2=np.array(y)
print(a1)
print(a2)

a3=np.vstack((a1,a2))

[ 2  4  6  8 10]
[22 24 26 28 30]


In [84]:
a3

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [86]:
#Create a 5x6 matrix with values ranging from 0 to 29 (both included) and 
#retrieve the value intersecting at 2nd row and 3rd column.

#CODING/OUTPUT FORMAT:

#Step 1:- Create an 5x6 matrix the values ranging from 0 to 29 (both included).

#Step 2:- Print the value intersecting at 2nd row and 3rd column.
    
a=np.arange(30).reshape(5,6)

In [88]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [89]:
a[1][2]

8