In [ ]:
#stacking

In [1]:
import numpy as np

In [2]:
x=np.arange(9).reshape(3,3)

In [3]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
y=np.arange(3).reshape(3,1)

In [5]:
print(y)

[[0]
 [1]
 [2]]


In [6]:
z=np.hstack((x,y))

In [7]:
z

array([[0, 1, 2, 0],
       [3, 4, 5, 1],
       [6, 7, 8, 2]])

In [8]:
c=np.vstack((x,y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [11]:
x=np.arange(9).reshape(3,3)

In [12]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
y=np.arange(3).reshape(1,3)
y

array([[0, 1, 2]])

In [14]:
c=np.vstack((x,y))

In [15]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [16]:
y=np.arange(27).reshape(3,3,3)

In [17]:
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
x=np.arange(3).reshape(3)
x

array([0, 1, 2])

In [19]:
v=np.dstack((y,x))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [20]:
v

NameError: name 'v' is not defined

In [21]:
def arr1(r=3,c=4,d=2):
    x=np.random.randint(25,size=(r,c,d))
    return x

In [22]:
a=arr1(2,3,4)

In [23]:
a

array([[[ 5,  1,  7, 13],
        [21, 23,  8,  3],
        [16, 12,  0,  2]],

       [[ 8, 20,  1, 21],
        [13,  8, 11,  2],
        [13, 11,  2,  7]]])

In [24]:
print(arr1(3,4))

[[[19  7]
  [15 13]
  [14 11]
  [13  8]]

 [[12 21]
  [ 0 17]
  [21  9]
  [10 15]]

 [[17 16]
  [12 17]
  [ 6 18]
  [ 7  5]]]


In [25]:
print(arr1(1,10,5))

[[[15 18 20 23  2]
  [ 7 13  8  8  0]
  [22  1  5  7 15]
  [ 3 21 10  5  3]
  [ 7 14  4  1 13]
  [16 13  4 20 23]
  [ 1 19 12 11  7]
  [ 6 22 12 24 10]
  [23 21  3 17  6]
  [ 1 13  4 21  4]]]


In [26]:
def arr2(r,c,d):
    x=np.random.randint(10,size=(r,c,d))
    return x

In [27]:
print(arr2(2,3,4))

[[[8 5 6 2]
  [9 4 0 1]
  [4 4 8 7]]

 [[4 5 1 5]
  [0 8 6 7]
  [9 6 7 0]]]


In [28]:
def arr2(r,c,d):
    x=np.random.randint(-10,-1,size=(r,c,d))
    return x

In [29]:
print(arr2(3,3,3))

[[[ -9  -7  -5]
  [ -5  -3  -6]
  [ -6  -6  -9]]

 [[ -2  -9  -8]
  [ -3  -5  -8]
  [-10  -2  -8]]

 [[ -7  -4 -10]
  [ -7  -7 -10]
  [ -4 -10 -10]]]


In [30]:
def arr2(r,c,d):
    x=np.random.randint(25,size=(r,c,d))
    return x

In [31]:
a1=arr2(3,3,3)

In [32]:
print(a1)

[[[10 22  4]
  [ 6 16  8]
  [12  5  5]]

 [[24 13 17]
  [ 4  7  6]
  [ 5  7 13]]

 [[15  9  5]
  [ 1  1 13]
  [ 2 22 20]]]


In [33]:
print(a1[a1%2!=0])

[ 5  5 13 17  7  5  7 13 15  9  5  1  1 13]


In [34]:
print(a1[(a1>10)&(a1<20)])

[16 12 13 17 13 15 13]


# Pandas

In [35]:
import pandas as pd

In [36]:
s1=pd.Series([10,20,30])

In [37]:
print(s1)

0    10
1    20
2    30
dtype: int64


In [38]:
type(s1)

pandas.core.series.Series

In [39]:
s2=pd.DataFrame(s1)         #creating the dataframe

In [40]:
print(s2)

    0
0  10
1  20
2  30


In [41]:
s2["New Entry"]="enter here"        

In [42]:
s2

0   New Entry
0  10  enter here
1  20  enter here
2  30  enter here

In [43]:
list(s2)

[0, 'New Entry']

In [44]:
print(list(s2))

[0, 'New Entry']


In [45]:
s1=pd.Series(np.random.randint(4,size=(3)))     #creating the series of random numbers

In [46]:
s1

0    0
1    3
2    3
dtype: int32

In [47]:
s1=pd.Series([10,20,30],index=["one","two","three"])        #user defined indexing

In [48]:
s1

one      10
two      20
three    30
dtype: int64

In [49]:
a=list(range(10,15))
s3=pd.Series([11,22,33,44,55],index=[a])

In [50]:
s3

10    11
11    22
12    33
13    44
14    55
dtype: int64

In [51]:
s4=s3[[1]]
print(s4)

11    22
dtype: int64


In [52]:
s3=["12"]

In [53]:
s3

['12']

In [54]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [55]:
s3

['12']

In [56]:
print(s3+4)      #broadcasting

TypeError: can only concatenate list (not "int") to list

In [57]:
print(s3)
s30=s3[s3>30]
print(s30)

['12']


TypeError: '>' not supported between instances of 'list' and 'int'

In [58]:
d1=pd.DataFrame({"IT":["Tcs","INFY","WIPRO","HCL","COGN","sasken"],"Energy":["ongc","IOL","HP","BP","ESSAR","RPL"],"FMCG":["HUI","ITC","PG","NSTLE","PARLE","BRIT"]})

In [59]:
d1

IT Energy   FMCG
0     Tcs   ongc    HUI
1    INFY    IOL    ITC
2   WIPRO     HP     PG
3     HCL     BP  NSTLE
4    COGN  ESSAR  PARLE
5  sasken    RPL   BRIT

In [60]:
print(d1["Energy"])

0     ongc
1      IOL
2       HP
3       BP
4    ESSAR
5      RPL
Name: Energy, dtype: object


In [61]:
d1=pd.DataFrame({"IT":["Tcs","INFY","WIPRO","HCL","COGN","sasken"],"Energy":["ongc","IOL","HP","BP","ESSAR","RPL"],"FMCG":["HUI","ITC","PG","NSTLE","PARLE","BRIT"]},index=["a","b","c","d","e","f"])

In [62]:
d1

IT Energy   FMCG
a     Tcs   ongc    HUI
b    INFY    IOL    ITC
c   WIPRO     HP     PG
d     HCL     BP  NSTLE
e    COGN  ESSAR  PARLE
f  sasken    RPL   BRIT

In [63]:
d1.head(2)

IT Energy FMCG
a   Tcs   ongc  HUI
b  INFY    IOL  ITC

In [64]:
d1.tail(2)

IT Energy   FMCG
e    COGN  ESSAR  PARLE
f  sasken    RPL   BRIT

In [65]:
d1["New Entry"]="enter the value"

In [66]:
d1

IT Energy   FMCG        New Entry
a     Tcs   ongc    HUI  enter the value
b    INFY    IOL    ITC  enter the value
c   WIPRO     HP     PG  enter the value
d     HCL     BP  NSTLE  enter the value
e    COGN  ESSAR  PARLE  enter the value
f  sasken    RPL   BRIT  enter the value

In [67]:
d1["Energy"]

a     ongc
b      IOL
c       HP
d       BP
e    ESSAR
f      RPL
Name: Energy, dtype: object

In [68]:
d1["Year"]="2019"

In [69]:
d1

IT Energy   FMCG        New Entry  Year
a     Tcs   ongc    HUI  enter the value  2019
b    INFY    IOL    ITC  enter the value  2019
c   WIPRO     HP     PG  enter the value  2019
d     HCL     BP  NSTLE  enter the value  2019
e    COGN  ESSAR  PARLE  enter the value  2019
f  sasken    RPL   BRIT  enter the value  2019

In [70]:
del d1["New Entry"]

In [71]:
d1

IT Energy   FMCG  Year
a     Tcs   ongc    HUI  2019
b    INFY    IOL    ITC  2019
c   WIPRO     HP     PG  2019
d     HCL     BP  NSTLE  2019
e    COGN  ESSAR  PARLE  2019
f  sasken    RPL   BRIT  2019

In [72]:
d1.drop("f")

IT Energy   FMCG  Year
a    Tcs   ongc    HUI  2019
b   INFY    IOL    ITC  2019
c  WIPRO     HP     PG  2019
d    HCL     BP  NSTLE  2019
e   COGN  ESSAR  PARLE  2019

In [73]:
d1

IT Energy   FMCG  Year
a     Tcs   ongc    HUI  2019
b    INFY    IOL    ITC  2019
c   WIPRO     HP     PG  2019
d     HCL     BP  NSTLE  2019
e    COGN  ESSAR  PARLE  2019
f  sasken    RPL   BRIT  2019

In [74]:
d1["a"]

KeyError: 'a'

In [75]:
d2=d1.T           # Transpose of a DataFrame
d2

a     b      c      d      e       f
IT       Tcs  INFY  WIPRO    HCL   COGN  sasken
Energy  ongc   IOL     HP     BP  ESSAR     RPL
FMCG     HUI   ITC     PG  NSTLE  PARLE    BRIT
Year    2019  2019   2019   2019   2019    2019

In [76]:
print(d1.iloc[1:3])     ## accesing columns of a dataframe

      IT Energy FMCG  Year
b   INFY    IOL  ITC  2019
c  WIPRO     HP   PG  2019


In [77]:
d1.head(3)[1:]

IT Energy FMCG  Year
b   INFY    IOL  ITC  2019
c  WIPRO     HP   PG  2019

In [78]:
print(d1)

       IT Energy   FMCG  Year
a     Tcs   ongc    HUI  2019
b    INFY    IOL    ITC  2019
c   WIPRO     HP     PG  2019
d     HCL     BP  NSTLE  2019
e    COGN  ESSAR  PARLE  2019
f  sasken    RPL   BRIT  2019


In [79]:
print(d1.iloc[:,:2])

       IT Energy
a     Tcs   ongc
b    INFY    IOL
c   WIPRO     HP
d     HCL     BP
e    COGN  ESSAR
f  sasken    RPL


In [80]:
print(d1.iloc[2:,:3])     

       IT Energy   FMCG
c   WIPRO     HP     PG
d     HCL     BP  NSTLE
e    COGN  ESSAR  PARLE
f  sasken    RPL   BRIT


In [81]:
print(d1.iloc[:,[0,2]])

       IT   FMCG
a     Tcs    HUI
b    INFY    ITC
c   WIPRO     PG
d     HCL  NSTLE
e    COGN  PARLE
f  sasken   BRIT


In [82]:
print(d1.iloc[[0,2],[0,2]])

      IT FMCG
a    Tcs  HUI
c  WIPRO   PG


In [83]:
help(np.rank)

Help on function rank in module numpy:

rank(a)
    Return the number of dimensions of an array.
    
    .. note::
        This function is deprecated in NumPy 1.9 to avoid confusion with
        `numpy.linalg.matrix_rank`. The ``ndim`` attribute or function
        should be used instead.
    
    See Also
    --------
    ndim : equivalent non-deprecated function
    
    Notes
    -----
    In the old Numeric package, `rank` was the term used for the number of
    dimensions, but in NumPy `ndim` is used instead.



In [84]:
np.rank(d1)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  """Entry point for launching an IPython kernel.


2

In [85]:
d2

a     b      c      d      e       f
IT       Tcs  INFY  WIPRO    HCL   COGN  sasken
Energy  ongc   IOL     HP     BP  ESSAR     RPL
FMCG     HUI   ITC     PG  NSTLE  PARLE    BRIT
Year    2019  2019   2019   2019   2019    2019

In [86]:
d1

IT Energy   FMCG  Year
a     Tcs   ongc    HUI  2019
b    INFY    IOL    ITC  2019
c   WIPRO     HP     PG  2019
d     HCL     BP  NSTLE  2019
e    COGN  ESSAR  PARLE  2019
f  sasken    RPL   BRIT  2019

In [87]:
d1.loc["a"]          ### accesing rows of dataframe 

IT         Tcs
Energy    ongc
FMCG       HUI
Year      2019
Name: a, dtype: object

In [88]:
d1.loc["b"]

IT        INFY
Energy     IOL
FMCG       ITC
Year      2019
Name: b, dtype: object

In [89]:
d1.loc[["a","c"],["IT","Energy","Year"]]      ## accessing multiple rows with selected columns

IT Energy  Year
a    Tcs   ongc  2019
c  WIPRO     HP  2019

In [90]:
d1.loc["a":"d","Energy"]                    ## in loc() function start and stop both will be included, i.e , d will also be printed

a    ongc
b     IOL
c      HP
d      BP
Name: Energy, dtype: object

In [91]:
d1.loc["a":"f":2,"Energy":"Year"] 

Energy   FMCG  Year
a   ongc    HUI  2019
c     HP     PG  2019
e  ESSAR  PARLE  2019

# how to reindex data

In [92]:
d3=d1.reindex(index=["e","b"],columns=["Year","IT"])     ## we are accessing the data as per our needs

In [93]:
d3

Year    IT
e  2019  COGN
b  2019  INFY

In [94]:
d1

IT Energy   FMCG  Year
a     Tcs   ongc    HUI  2019
b    INFY    IOL    ITC  2019
c   WIPRO     HP     PG  2019
d     HCL     BP  NSTLE  2019
e    COGN  ESSAR  PARLE  2019
f  sasken    RPL   BRIT  2019

In [95]:
d4=d1.reindex([11,12,13,14,15,17],fill_value=0)

In [96]:
d4

IT Energy FMCG Year
11  0      0    0    0
12  0      0    0    0
13  0      0    0    0
14  0      0    0    0
15  0      0    0    0
17  0      0    0    0

In [97]:
d5=pd.concat([d1,d4])     ### combining of two data frames

In [98]:
d5

IT Energy   FMCG  Year
a      Tcs   ongc    HUI  2019
b     INFY    IOL    ITC  2019
c    WIPRO     HP     PG  2019
d      HCL     BP  NSTLE  2019
e     COGN  ESSAR  PARLE  2019
f   sasken    RPL   BRIT  2019
11       0      0      0     0
12       0      0      0     0
13       0      0      0     0
14       0      0      0     0
15       0      0      0     0
17       0      0      0     0

# Droping of dublicates from dataframe

drop_duplicates()

drop_duplicates(["Name],keep="last")

In [99]:
d5.drop_duplicates()

IT Energy   FMCG  Year
a      Tcs   ongc    HUI  2019
b     INFY    IOL    ITC  2019
c    WIPRO     HP     PG  2019
d      HCL     BP  NSTLE  2019
e     COGN  ESSAR  PARLE  2019
f   sasken    RPL   BRIT  2019
11       0      0      0     0

In [100]:
d5[d5.IT != "HCL"]        ## row that have hcl will be removed

IT Energy   FMCG  Year
a      Tcs   ongc    HUI  2019
b     INFY    IOL    ITC  2019
c    WIPRO     HP     PG  2019
e     COGN  ESSAR  PARLE  2019
f   sasken    RPL   BRIT  2019
11       0      0      0     0
12       0      0      0     0
13       0      0      0     0
14       0      0      0     0
15       0      0      0     0
17       0      0      0     0

In [101]:
d5.drop(d5.index[2])      # row c is removed

IT Energy   FMCG  Year
a      Tcs   ongc    HUI  2019
b     INFY    IOL    ITC  2019
d      HCL     BP  NSTLE  2019
e     COGN  ESSAR  PARLE  2019
f   sasken    RPL   BRIT  2019
11       0      0      0     0
12       0      0      0     0
13       0      0      0     0
14       0      0      0     0
15       0      0      0     0
17       0      0      0     0

In [102]:
d6=d5.drop_duplicates()
d6

IT Energy   FMCG  Year
a      Tcs   ongc    HUI  2019
b     INFY    IOL    ITC  2019
c    WIPRO     HP     PG  2019
d      HCL     BP  NSTLE  2019
e     COGN  ESSAR  PARLE  2019
f   sasken    RPL   BRIT  2019
11       0      0      0     0

In [103]:
print(d6.drop("IT",axis=1))     # for column : axis = 1, for rows: axis =0, for depth: axis =2

   Energy   FMCG  Year
a    ongc    HUI  2019
b     IOL    ITC  2019
c      HP     PG  2019
d      BP  NSTLE  2019
e   ESSAR  PARLE  2019
f     RPL   BRIT  2019
11      0      0     0


In [104]:
print(d6["Year"])

a     2019
b     2019
c     2019
d     2019
e     2019
f     2019
11       0
Name: Year, dtype: object


# d5.sort_values(by=" ")    this is used to sort data frame by values

# eg.

# d5.sort_values(by="score", ascending=0)

# d5.sort_values(by=["score","age"],ascending=[True,False])    #priority is to sort by score first
# d5.sort_index(ascending=True)    this is used to sort by index

In [105]:
d5

IT Energy   FMCG  Year
a      Tcs   ongc    HUI  2019
b     INFY    IOL    ITC  2019
c    WIPRO     HP     PG  2019
d      HCL     BP  NSTLE  2019
e     COGN  ESSAR  PARLE  2019
f   sasken    RPL   BRIT  2019
11       0      0      0     0
12       0      0      0     0
13       0      0      0     0
14       0      0      0     0
15       0      0      0     0
17       0      0      0     0

In [106]:
d5["Score"]=(97,90,75,56,32,10,29,46,66,84,10,25,)

In [107]:
d7=d5.loc["a":"f"]
d7

IT Energy   FMCG  Year  Score
a     Tcs   ongc    HUI  2019     97
b    INFY    IOL    ITC  2019     90
c   WIPRO     HP     PG  2019     75
d     HCL     BP  NSTLE  2019     56
e    COGN  ESSAR  PARLE  2019     32
f  sasken    RPL   BRIT  2019     10

In [131]:
d7["score_ranked22"]=d7['Score'].rank(ascending=0) 

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [132]:
d7

IT Energy   FMCG  Year  Score  score_ranked22  Rank
a     Tcs   ongc    HUI  2019     97             1.0   6.0
b    INFY    IOL    ITC  2019     90             2.0   5.0
c   WIPRO     HP     PG  2019     75             3.0   4.0
d     HCL     BP  NSTLE  2019     56             4.0   3.0
e    COGN  ESSAR  PARLE  2019     32             5.0   2.0
f  sasken    RPL   BRIT  2019     10             6.0   1.0

In [115]:
d5["sc5"]=d5["Score"].rank(ascending=0,method="dense")

In [116]:
d5

IT Energy   FMCG  Year  Score   sc5
a      Tcs   ongc    HUI  2019     97   1.0
b     INFY    IOL    ITC  2019     90   2.0
c    WIPRO     HP     PG  2019     75   4.0
d      HCL     BP  NSTLE  2019     56   6.0
e     COGN  ESSAR  PARLE  2019     32   8.0
f   sasken    RPL   BRIT  2019     10  11.0
11       0      0      0     0     29   9.0
12       0      0      0     0     46   7.0
13       0      0      0     0     66   5.0
14       0      0      0     0     84   3.0
15       0      0      0     0     10  11.0
17       0      0      0     0     25  10.0

In [117]:
d5["sc5"]=d5["Score"].rank(ascending=1)

In [118]:
d5

IT Energy   FMCG  Year  Score   sc5
a      Tcs   ongc    HUI  2019     97  12.0
b     INFY    IOL    ITC  2019     90  11.0
c    WIPRO     HP     PG  2019     75   9.0
d      HCL     BP  NSTLE  2019     56   7.0
e     COGN  ESSAR  PARLE  2019     32   5.0
f   sasken    RPL   BRIT  2019     10   1.5
11       0      0      0     0     29   4.0
12       0      0      0     0     46   6.0
13       0      0      0     0     66   8.0
14       0      0      0     0     84  10.0
15       0      0      0     0     10   1.5
17       0      0      0     0     25   3.0

In [134]:
d5["sc5"]=d5['sc5'].rank(ascending=1) 

In [121]:
d5

IT Energy   FMCG  Year  Score   sc5
a      Tcs   ongc    HUI  2019     97  12.0
b     INFY    IOL    ITC  2019     90  11.0
c    WIPRO     HP     PG  2019     75   9.0
d      HCL     BP  NSTLE  2019     56   7.0
e     COGN  ESSAR  PARLE  2019     32   5.0
f   sasken    RPL   BRIT  2019     10   1.5
11       0      0      0     0     29   4.0
12       0      0      0     0     46   6.0
13       0      0      0     0     66   8.0
14       0      0      0     0     84  10.0
15       0      0      0     0     10   1.5
17       0      0      0     0     25   3.0

In [124]:
d7

IT Energy   FMCG  Year  Score  score_ranked22  Rank  sc5
a     Tcs   ongc    HUI  2019     97             6.0   6.0  1.0
b    INFY    IOL    ITC  2019     90             5.0   5.0  2.0
c   WIPRO     HP     PG  2019     75             4.0   4.0  3.0
d     HCL     BP  NSTLE  2019     56             3.0   3.0  4.0
e    COGN  ESSAR  PARLE  2019     32             2.0   2.0  5.0
f  sasken    RPL   BRIT  2019     10             1.0   1.0  6.0

In [129]:
del d7["sc5"]

In [133]:
d7

IT Energy   FMCG  Year  Score  score_ranked22  Rank
a     Tcs   ongc    HUI  2019     97             1.0   6.0
b    INFY    IOL    ITC  2019     90             2.0   5.0
c   WIPRO     HP     PG  2019     75             3.0   4.0
d     HCL     BP  NSTLE  2019     56             4.0   3.0
e    COGN  ESSAR  PARLE  2019     32             5.0   2.0
f  sasken    RPL   BRIT  2019     10             6.0   1.0