In [54]:
import numpy as np

In [55]:
a=[111,222,333]
ar=np.array(a)

In [56]:
ar

array([111, 222, 333])

In [57]:
print(a)       

[111, 222, 333]


In [58]:
type(a)

list

In [59]:
print(ar)

[111 222 333]


In [60]:
type(ar)

numpy.ndarray

In [61]:
ar.shape     #Doubt

(3,)

In [62]:
ar.itemsize

4

In [63]:
ar.ndim

1

In [64]:
ar.size     #no. of elements

3

In [65]:
ar.itemsize*ar.size

12

In [66]:
print(ar[1])

222


In [67]:
list1=[111,222,333]
list2=[444,555,666]
ar1=np.array(list1)
ar2=np.array(list2)
ar3=ar1+ar2                # arithmetic addition 

In [68]:
print(ar3)

[555 777 999]


In [69]:
ar4=ar1*ar2
print(ar4)

[ 49284 123210 221778]


In [70]:
ar4.shape

(3,)

In [71]:
ar4.itemsize

4

In [72]:
ar4.size

3

In [73]:
type(ar4)

numpy.ndarray

# Two dimensional arrays

In [74]:
list1=[[111,222,333],[444,555,666],[777,888,999]]
print(list1) 

[[111, 222, 333], [444, 555, 666], [777, 888, 999]]


In [75]:
ar5=np.array(list1)

In [76]:
ar5

array([[111, 222, 333],
       [444, 555, 666],
       [777, 888, 999]])

In [77]:
print(ar5)

[[111 222 333]
 [444 555 666]
 [777 888 999]]


In [78]:
ar5.shape

(3, 3)

In [79]:
ar5.itemsize      #bytes taken by the element

4

In [80]:
ar5.size         #total no. of elements

9

In [81]:
ar5.strides

(12, 4)

In [82]:
ar5.ndim        #dimensions of array

2

In [83]:
len(ar5)

3

In [84]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [85]:
#slicing
  
x=ar5[1:3,1:3]         add 1 in column part

SyntaxError: invalid syntax (<ipython-input-85-e8bbbab06d64>, line 3)

In [ ]:
x      

In [ ]:
y=ar5[1:3,1:2]

In [ ]:
y

In [ ]:
z=ar5[[1,2,0],[0,1,1]]      # this is not slicing but simple co ordinates for elements and read as that are (1,0), (2,1) and (0,1)

In [ ]:
z

# Accessing values of string through slicing

## mystring[N:M:STEP]    # starting point=N, end point=M(excluding M) ,Step =+1 by default

# eg: 

mystring="ABCDEFGHIJKL"
print(mystring[1:7])
 
output : BCDEFG





In [ ]:
a="ABCDEFGHIJKL"

In [ ]:
print(a[1:7])

In [ ]:
print(a[-8:-2])

In [ ]:
print(a[4:-2])

In [ ]:
ar3

In [ ]:
ar5

In [ ]:
ar6=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

In [ ]:
ar6

In [86]:
ar6.shape

NameError: name 'ar6' is not defined

In [ ]:
ar7=ar6.reshape(3,6)

In [ ]:
ar7

In [ ]:
ar8=ar6.reshape(9,2)
print(ar8)

In [ ]:
ar9=np.transpose(ar6)          #transpose function

In [ ]:
ar9

In [ ]:
ar10=ar6.reshape(3,2,3)

In [ ]:
ar10

In [ ]:
ar10.ndim

In [ ]:
ar10.size

In [ ]:
ar10.shape     # 3 = rows, 2 = columns, 3 = depth

In [ ]:
ar10[0:3, 0:3, 0:1]       #0:3 for row, 0:3 for column and 0:1 for depth

In [ ]:
list1=[[[1,2],[3,4],[5,6],[7,8],[9,10]],[[11,12],[13,14],[15,16],[17,18],[19,20]],[[21,22],[23,24],[25,26],[27,28],[29,30]]]

In [ ]:
list1

In [ ]:
ar11=np.array(list1)

In [ ]:
ar11

In [ ]:
print(ar11[1,2,1])

In [ ]:
list2=[[[111,112,113],[121,122,123],[131,132,133],[141,142,143]],[[211,212,213],[221,222,223],[231,232,233],[241,242,243]],[[311,312,313],[321,322,323],[331,332,333],[341,342,343]],[[411,412,413],[421,422,423],[431,432,
433],[441,442,443]],[[511,512,513],[521,522,523],[531,532,533],[541,542,543]]]

In [ ]:
list2

In [ ]:
arr12=np.array(list2)

In [ ]:
arr12

In [ ]:
for i in range(len(arr12)):
   for c in range(len(arr12[0])):
        for d in range(len(arr12[0][0])):
            print("row, column, depth : ",i,c,d,":", arr12[i][c][d])
    

In [ ]:
import pandas as pd

In [ ]:
arr13=arr12.reshape(12,5)

In [ ]:
ary=pd.DataFrame(arr13)

In [ ]:
ary

In [ ]:
print(arr12[[0,2,1],[0,0,0],[0,1,1]])

In [ ]:
print(arr12[0:4,0:3,0:2])

In [ ]:
arr12[2,0:5,1:3]

In [ ]:
a=np.arange(1,25,dtype=np.int32).reshape(6,4)


In [ ]:
a

In [ ]:
a+2      #broadcasting

In [ ]:
a=np.arange(1,25).reshape(6,2,2)


In [ ]:
a

In [ ]:
a=a+[1,2]

In [87]:
a

[111, 222, 333]

In [88]:
a=np.arange(1,25).reshape(6,4)


In [89]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [90]:
a+[2,3,4,5]

array([[ 3,  5,  7,  9],
       [ 7,  9, 11, 13],
       [11, 13, 15, 17],
       [15, 17, 19, 21],
       [19, 21, 23, 25],
       [23, 25, 27, 29]])

In [91]:
a[1,1]+[1,9]

array([ 7, 15])

In [92]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [93]:
a[1,2]+[1,1]     

array([8, 8])

In [94]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [95]:
a=np.arange(1,25).reshape(6,4)


In [96]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [97]:
print(np.hsplit(a,2))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]


In [98]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [99]:
x=np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [120]:
print(np.hsplit(x,2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [121]:
y=np.array([1,3])

In [122]:
y

array([1, 3])

In [123]:
x=np.hsplit(x,y)
print(x)

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [104]:
y=np.array([1,3])
x=np.hsplit(x,y)
print(x)

ValueError: could not broadcast input array from shape (4,1) into shape (4)

In [105]:
x=np.hsplit(x,y)
print(x)

ValueError: could not broadcast input array from shape (4,1) into shape (4)

In [116]:
x=np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [117]:
z=np.hsplit(x,y)
print(z)

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [ ]:
x=np.hsplit(x,y)
print(x)

In [ ]:
z=np.hsplit(x,y)
print(z)

In [106]:
z=np.vsplit(x,y)
print(z)

ValueError: could not broadcast input array from shape (4,1) into shape (4)

In [114]:
x=np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [115]:
z=np.vsplit(x,y)
print(z)

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [ ]:
z=np.vsplit(x,y)
print(z)

In [ ]:
z=np.vsplit(x,np.array[1,2,3])
print(z)

In [ ]:
x=np.arange(16).reshape(4,4)
print(x)

In [ ]:
z=np.vsplit(x,np.array([1,2,3]))     #:1,1:2,2:3,3:
print(z)

In [ ]:
c=pd.DataFrame(z)

In [ ]:
x=np.arange(16).reshape(4,4)
print(x)

In [111]:
z=np.vsplit(x,y)
print(z)

ValueError: could not broadcast input array from shape (4,1) into shape (4)

In [ ]:
c=pd.DataFrame(z)

In [ ]:
c

In [ ]:
l=np.vsplit(x,np.array([1,2,3]))     #:1,1:2,2:3,3:
print(l)

In [ ]:
d=pd.DataFrame(l)

In [ ]:
np.dsplit(x,2)

In [ ]:
x=np.arange(16).reshape(4,4)
print(x)

In [ ]:
np.dsplit(x,2)

In [ ]:
x=np.arange(1,25).reshape(6,2,2)
print(x)


In [107]:
np.dsplit(x,2)

ValueError: could not broadcast input array from shape (4,1) into shape (4)

In [ ]:
h=np.zeros((3,3,3))

In [ ]:
h

In [ ]:
x=np.arange(16).reshape(4,2,2)
print(x)

In [ ]:
j=np.dsplit(x,2)

In [ ]:
j

In [ ]:
k=np.hsplit(x,2)
print(k)

In [ ]:
g=np.vsplit(x,2)
print(g)

# ravel function for converting n dimensional array into 1


In [ ]:
x=np.arange(16).reshape(4,2,2)
print(x)

In [ ]:
s=x.ravel()
s

In [ ]:
print(x.max())     #maximum value

In [ ]:
print(x.min())     #minimmum value

In [ ]:
print(x.mean())        #mean value

In [ ]:
print(x.var())    #Variance

In [ ]:
print(x.std())      #standard deviation

In [ ]:
x=np.arange(16).reshape(4,2,2)
print(x)