In [3]:
import pandas as pd
import numpy as np

In [4]:
train1=pd.read_csv("G:\\Datasets\\FoodChallenge\\train.csv")

In [5]:
train2=pd.read_csv("G:\\Datasets\\FoodChallenge\\Meal_info.csv")

In [6]:
train3=pd.read_csv("G:\\Datasets\\FoodChallenge\\fulfilment_center_info.csv")

In [7]:
test=pd.read_csv("G:\Datasets\FoodChallenge\\test.csv")

In [8]:
train2.head()

meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

In [9]:
train3.head()

center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [10]:
train_new=pd.merge(train1,train2,how="inner")

In [11]:
train_new.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1040403     1         24     1885          136.83      136.83   
2  1103215     1         11     1885          136.83      136.83   
3  1034383     1         83     1885          121.31      120.31   
4  1118999     1         32     1885          114.52      113.52   

   emailer_for_promotion  homepage_featured  num_orders   category cuisine  
0                      0                  0         177  Beverages    Thai  
1                      0                  0        1498  Beverages    Thai  
2                      0                  0         959  Beverages    Thai  
3                      0                  1        1025  Beverages    Thai  
4                      0                  1         445  Beverages    Thai

In [12]:
train_new=pd.merge(train_new,train3,how="inner")

In [13]:
train_new.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1018704     2         55     1885          135.83      152.29   
2  1196273     3         55     1885          132.92      133.92   
3  1116527     4         55     1885          135.86      134.86   
4  1343872     5         55     1885          146.50      147.50   

   emailer_for_promotion  homepage_featured  num_orders   category cuisine  \
0                      0                  0         177  Beverages    Thai   
1                      0                  0         323  Beverages    Thai   
2                      0                  0          96  Beverages    Thai   
3                      0                  0         163  Beverages    Thai   
4                      0                  0         215  Beverages    Thai   

   city_code  region_code center_type  op_area  
0        647           56      TYPE_C      2.0  
1        647           56      TYPE_C      2.0  
2        647           56      TYPE_C      2.0  
3        647           56      TYPE_C      2.0  
4        647           56      TYPE_C      2.0

In [14]:
train_new.shape

(456548, 15)

In [15]:
train_new.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
category                 0
cuisine                  0
city_code                0
region_code              0
center_type              0
op_area                  0
dtype: int64

In [16]:
test.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0

In [17]:
train1.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1466964     1         55     1993          136.83      135.83   
2  1346989     1         55     2539          134.86      135.86   
3  1338232     1         55     2139          339.50      437.53   
4  1448490     1         55     2631          243.50      242.50   

   emailer_for_promotion  homepage_featured  num_orders  
0                      0                  0         177  
1                      0                  0         270  
2                      0                  0         189  
3                      0                  0          54  
4                      0                  0          40

In [18]:
# Scalling the Data

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_train = pd.DataFrame(sc.fit_transform(train1), columns=train1.columns)
scaled_train.head()

id      week  center_id   meal_id  checkout_price  base_price  \
0  0.896845 -1.776494  -0.589577 -0.254535       -1.277687   -1.256048   
1  1.502326 -1.776494  -0.589577 -0.057246       -1.277687   -1.358465   
2  0.671213 -1.776494  -0.589577  0.940160       -1.290568   -1.358278   
3  0.610550 -1.776494  -0.589577  0.209460        0.047477    0.518763   
4  1.374349 -1.776494  -0.589577  1.108221       -0.580222   -0.694746   

   emailer_for_promotion  homepage_featured  num_orders  
0              -0.297187          -0.350123   -0.214367  
1              -0.297187          -0.350123    0.020527  
2              -0.297187          -0.350123   -0.184058  
3              -0.297187          -0.350123   -0.525034  
4              -0.297187          -0.350123   -0.560395

In [20]:
scaled_test = pd.DataFrame(sc.fit_transform(test), columns=test.columns)
scaled_test.head()

id      week  center_id   meal_id  checkout_price  base_price  \
0 -1.527818 -1.563469   -0.58546 -0.268769       -1.193987   -1.272230   
1 -0.841255 -1.563469   -0.58546 -0.071397       -1.180991   -1.272230   
2 -0.248126 -1.563469   -0.58546  0.926427       -1.200290   -1.272037   
3 -1.149990 -1.563469   -0.58546  1.094558       -1.168579   -1.253474   
4  1.057537 -1.563469   -0.58546 -1.432897       -1.156168   -1.241163   

   emailer_for_promotion  homepage_featured  
0              -0.266764          -0.297591  
1              -0.266764          -0.297591  
2              -0.266764          -0.297591  
3              -0.266764          -0.297591  
4              -0.266764          -0.297591

In [21]:
y=scaled_train.num_orders
y.head()

0   -0.214367
1    0.020527
2   -0.184058
3   -0.525034
4   -0.560395
Name: num_orders, dtype: float64

In [22]:
x=scaled_train.drop("num_orders",axis=1)

In [23]:
x.head()

id      week  center_id   meal_id  checkout_price  base_price  \
0  0.896845 -1.776494  -0.589577 -0.254535       -1.277687   -1.256048   
1  1.502326 -1.776494  -0.589577 -0.057246       -1.277687   -1.358465   
2  0.671213 -1.776494  -0.589577  0.940160       -1.290568   -1.358278   
3  0.610550 -1.776494  -0.589577  0.209460        0.047477    0.518763   
4  1.374349 -1.776494  -0.589577  1.108221       -0.580222   -0.694746   

   emailer_for_promotion  homepage_featured  
0              -0.297187          -0.350123  
1              -0.297187          -0.350123  
2              -0.297187          -0.350123  
3              -0.297187          -0.350123  
4              -0.297187          -0.350123

In [24]:
# Linear Regression

In [25]:
from sklearn.linear_model import LinearRegression
Devil = LinearRegression()



In [26]:
Devil.fit(pd.DataFrame(x),y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
pred1=Devil.predict(scaled_test)

In [28]:
pred1

array([ 0.26436385,  0.26433026,  0.27368979, ..., -0.05276565,
       -0.05302463,  0.02856952])

In [38]:
new = sc.fit_transform(pd.DataFrame(train1.num_orders))

In [39]:
pred=sc.inverse_transform(pred1)

In [40]:
pred

array([366.54032255, 366.5270209 , 370.23266901, ..., 240.98165993,
       240.87912267, 273.18407415])

In [38]:
solution = pd.DataFrame({"id":test.id, "num_orders":pred})

In [39]:
solution.to_csv("Food_LR.csv", index = False)

In [40]:
len(pred[pred<0])

1579

In [41]:
# Random Forest     # 65.5

In [42]:
train1.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1466964     1         55     1993          136.83      135.83   
2  1346989     1         55     2539          134.86      135.86   
3  1338232     1         55     2139          339.50      437.53   
4  1448490     1         55     2631          243.50      242.50   

   emailer_for_promotion  homepage_featured  num_orders  
0                      0                  0         177  
1                      0                  0         270  
2                      0                  0         189  
3                      0                  0          54  
4                      0                  0          40

In [43]:
test.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0

In [44]:
y=train1.num_orders

In [45]:
x=train1.drop("num_orders",axis=1)

In [46]:
from sklearn.ensemble import RandomForestRegressor
Baby = RandomForestRegressor()                                      


In [47]:
Baby.fit(pd.DataFrame(x),y)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [48]:
pred1=Baby.predict(test)
pred1

array([1009.1,  146.5,  173.6, ...,  380.9,  248.9,  299. ])

In [49]:
solution = pd.DataFrame({"id":test.id, "num_orders":pred1})

In [50]:
solution.to_csv("Food_RF.csv", index = False)

In [51]:
# Decision Tree         # 80.5

In [52]:
from sklearn.tree import DecisionTreeRegressor
Cutie = DecisionTreeRegressor()                                      


In [53]:
pred2=Cutie.fit(x,y).predict(test)

In [54]:
pred2

array([1187.,  459.,   94., ...,  121.,  271.,  365.])

In [55]:
solution = pd.DataFrame({"id":test.id, "num_orders":pred2})

In [56]:
solution.to_csv("Food_DT.csv", index = False)

In [94]:
# Feature Selection Using MLXtend         # 68

In [65]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs


In [84]:
sfs1 = sfs(Baby,k_features=5,cv=2)


In [85]:
sfs1 = sfs1.fit(train1.drop("num_orders",axis=1), train1.num_orders)


In [86]:
feat_cols = list(sfs1.k_feature_idx_)
print(feat_cols)

[0, 2, 3, 6, 7]


In [87]:
x.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1466964     1         55     1993          136.83      135.83   
2  1346989     1         55     2539          134.86      135.86   
3  1338232     1         55     2139          339.50      437.53   
4  1448490     1         55     2631          243.50      242.50   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0

In [88]:
x1=x.drop(["week","checkout_price","base_price"],axis=1)

In [89]:
test1=test.drop(["week","checkout_price","base_price"],axis=1)

In [90]:
Baby.fit(pd.DataFrame(x1),y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [91]:
pred3=Baby.predict(test1)
pred3

array([192.2, 178.7, 185.3, ..., 315.7, 515.6, 127.6])

In [92]:
solution = pd.DataFrame({"id":test.id, "num_orders":pred3})

In [93]:
solution.to_csv("Food_RF_MLX.csv", index = False)

In [67]:
# Retry      # wrong

In [33]:
train1.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1466964     1         55     1993          136.83      135.83   
2  1346989     1         55     2539          134.86      135.86   
3  1338232     1         55     2139          339.50      437.53   
4  1448490     1         55     2631          243.50      242.50   

   emailer_for_promotion  homepage_featured  num_orders  
0                      0                  0         177  
1                      0                  0         270  
2                      0                  0         189  
3                      0                  0          54  
4                      0                  0          40

In [34]:
train2.head()

meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

In [35]:
train3.head()

center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [36]:
train=pd.merge(train1,train2,how="inner")

In [37]:
train.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1040403     1         24     1885          136.83      136.83   
2  1103215     1         11     1885          136.83      136.83   
3  1034383     1         83     1885          121.31      120.31   
4  1118999     1         32     1885          114.52      113.52   

   emailer_for_promotion  homepage_featured  num_orders   category cuisine  
0                      0                  0         177  Beverages    Thai  
1                      0                  0        1498  Beverages    Thai  
2                      0                  0         959  Beverages    Thai  
3                      0                  1        1025  Beverages    Thai  
4                      0                  1         445  Beverages    Thai

In [38]:
train=pd.merge(train,train3,how="inner")

In [39]:
train.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1018704     2         55     1885          135.83      152.29   
2  1196273     3         55     1885          132.92      133.92   
3  1116527     4         55     1885          135.86      134.86   
4  1343872     5         55     1885          146.50      147.50   

   emailer_for_promotion  homepage_featured  num_orders   category cuisine  \
0                      0                  0         177  Beverages    Thai   
1                      0                  0         323  Beverages    Thai   
2                      0                  0          96  Beverages    Thai   
3                      0                  0         163  Beverages    Thai   
4                      0                  0         215  Beverages    Thai   

   city_code  region_code center_type  op_area  
0        647           56      TYPE_C      2.0  
1        647           56      TYPE_C      2.0  
2        647           56      TYPE_C      2.0  
3        647           56      TYPE_C      2.0  
4        647           56      TYPE_C      2.0

In [15]:
# scaling and dummification

In [40]:
dummytrain=pd.get_dummies(train)

In [41]:
dummytrain.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1018704     2         55     1885          135.83      152.29   
2  1196273     3         55     1885          132.92      133.92   
3  1116527     4         55     1885          135.86      134.86   
4  1343872     5         55     1885          146.50      147.50   

   emailer_for_promotion  homepage_featured  num_orders  city_code  ...  \
0                      0                  0         177        647  ...   
1                      0                  0         323        647  ...   
2                      0                  0          96        647  ...   
3                      0                  0         163        647  ...   
4                      0                  0         215        647  ...   

   category_Seafood  category_Soup  category_Starters  cuisine_Continental  \
0                 0              0                  0                    0   
1                 0              0                  0                    0   
2                 0              0                  0                    0   
3                 0              0                  0                    0   
4                 0              0                  0                    0   

   cuisine_Indian  cuisine_Italian  cuisine_Thai  center_type_TYPE_A  \
0               0                0             1                   0   
1               0                0             1                   0   
2               0                0             1                   0   
3               0                0             1                   0   
4               0                0             1                   0   

   center_type_TYPE_B  center_type_TYPE_C  
0                   0                   1  
1                   0                   1  
2                   0                   1  
3                   0                   1  
4                   0                   1  

[5 rows x 33 columns]

In [42]:
dummytrain.drop("id",inplace=True,axis=1)

In [37]:
from sklearn.preprocessing import StandardScaler
mms=StandardScaler()

scaled_train = pd.DataFrame(mms.fit_transform(dummytrain), columns=dummytrain.columns)
scaled_train.head()

NameError: name 'dummytrain' is not defined

In [45]:
y=scaled_train.num_orders

In [46]:
test.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0

In [48]:
test.drop("id",axis=1,inplace=True)

In [50]:
xtrain=scaled_train[test.columns]

# Linear Regression

In [52]:
from sklearn.linear_model import LinearRegression
Baby11 = LinearRegression()

In [54]:
Baby11.fit(xtrain,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [55]:
pred5=Baby11.predict(test)

In [56]:
pred5

array([-35.71837043, -35.25372008, -31.23761987, ..., -76.51481206,
       -77.14833561, -64.83974627])

In [36]:
new = mms.fit_transform(pd.DataFrame(train1.num_orders))

NameError: name 'mms' is not defined

In [59]:
pred5=mms.inverse_transform(pred5)

In [62]:
pred55=abs(pred5)

In [65]:
solution = pd.DataFrame({"id":test.id, "num_orders":pred55})

In [66]:
solution.to_csv("Food_LR_RETRY.csv", index = False)

# XGBOOST

In [2]:
from xgboost.sklearn import XGBRegressor


In [32]:
DAD=XGBRegressor()

In [52]:
DAD.fit(train1.drop("num_orders",axis=1),train1.num_orders)

C:\Users\Asus\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
C:\Users\Asus\Anaconda3\lib\site-packages\xgboost\core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[17:43:55] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [53]:
pred_1=DAD.predict(test)

In [54]:
pred_1

array([440.8252 , 331.22986, 197.32227, ..., 308.6252 , 237.8727 ,
       218.54631], dtype=float32)

In [41]:
pred_1=sc.inverse_transform(pred_1)

In [43]:
pred_1

array([368.7399 , 460.4323 , 244.37344, ..., 308.63635, 237.88362,
       218.55714], dtype=float32)

In [58]:
solution = pd.DataFrame({"id":test.id, "num_orders":abs(pred_1)})

In [59]:
solution.to_csv("Food_XGB.csv", index = False)

In [60]:
(solution.num_orders<0).value_counts()

False    32573
Name: num_orders, dtype: int64

In [51]:
pred1

array([ 0.26436385,  0.26433026,  0.27368979, ..., -0.05276565,
       -0.05302463,  0.02856952])

In [ ]:
abs()