In [1]:
import numpy as np

In [2]:
a=np.arange(1,10).reshape(3,3)


In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a=np.full((3,3),True,dtype=bool)          #full function is used to fill the array with one element
  

In [15]:
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
a=np.full((1,5),2,dtype=int)       
  

In [39]:
print(a)

[[2 2 2 2 2]]


In [40]:
a.shape

(1, 5)

In [ ]:
1,4,1:3

In [45]:
a=np.full((3,3),1,dtype=str)          #full function is used to fill the array with one element
  

In [46]:
a

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')