In [20]:
listx=[21,12,11131,314,122]

In [3]:
import pandas as pd

In [21]:
lis=[211121,121,212334,468,79886,12]

In [22]:
lis

[211121, 121, 212334, 468, 79886, 12]

In [23]:
listx.append(lis)

In [24]:
listx

[21, 12, 11131, 314, 122, [211121, 121, 212334, 468, 79886, 12]]

In [25]:
12 in listx

True

In [26]:
listx.count(12)

1

In [33]:
max(lis)

212334

In [35]:
min(lis)

12

In [36]:
listx.index(12)

1

In [42]:
a=[]
for i in range(0,25):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [45]:
import numpy as np
list_l =[[12,34,55,],[66,45,77],[45,77,88]]
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [46]:
test_array = [10, 11.5, 12, 13.5, 14,15] 
test_array[2:3]

[12]

In [47]:
demo_array = np.arange(10,21)
subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [48]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [49]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [51]:
demo_array=np.arange(0,10)
demo_array <3
demo_array[demo_array <6]
np.max(demo_array)

9

In [52]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
b = np.arange(0,10,2) 
c = a + b 
print (c[4])

13


In [4]:
series2 = pd.Series([10,20,30,40,50],index=["one","two","three","four","five"])

print(series2["two"]

20

In [7]:
 mydict = {'company':'toyota' , 'model':'corolla' , 'year':1994}

print(mydict)

{'company': 'toyota', 'model': 'corolla', 'year': 1994}
