In [2]:
import pandas as pd
import numpy as np
train=pd.read_csv("G:\Datasets\House_Price_Comp\housetrain.csv")
test=pd.read_csv("G:\Datasets\House_Price_Comp\housetest.csv")
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)


In [3]:
new_train=train.drop("Id",axis=1)
new_test=test.drop("Id",axis=1)

In [4]:
dummytrain=pd.get_dummies(new_train)
dummytest=pd.get_dummies(new_test)

In [5]:
dummytrain.shape

(1460, 289)

In [6]:
dummytest.shape

(1459, 270)

In [7]:
l1 = list(set(dummytrain.columns) - set(dummytest.columns))
dummytrain1 = dummytrain.drop(l1, axis = 1)

In [8]:
dummytrain1["SalePrice"]=dummytrain["SalePrice"]

In [9]:
dummytrain1.head()

MSSubClass  ScreenPorch  PoolArea  MiscVal  GarageYrBlt  GarageCars  \
0          60            0         0        0         2003           2   
1          20            0         0        0         1976           2   
2          60            0         0        0         2001           2   
3          70            0         0        0         1998           3   
4          60            0         0        0         2000           3   

   GarageArea  WoodDeckSF  OpenPorchSF  EnclosedPorch  X3SsnPorch  \
0         548           0           61              0           0   
1         460         298            0              0           0   
2         608           0           42              0           0   
3         642           0           35            272           0   
4         836         192           84              0           0   

   BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0             1             0         2         1             3             1   
1             0             1         2         0             3             1   
2             1             0         2         1             3             1   
3             1             0         1         0             3             1   
4             1             0         2         1             4             1   

   TotRmsAbvGrd  Fireplaces  X1stFlrSF  X2ndFlrSF  LowQualFinSF  GrLivArea  \
0             8           0        856        854             0       1710   
1             6           1       1262          0             0       1262   
2             6           1        920        866             0       1786   
3             7           1        961        756             0       1717   
4             9           1       1145       1053             0       2198   

   BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  MasVnrArea  YearBuilt  \
0         706           0        150          856         196       2003   
1         978           0        284         1262           0       1976   
2         486           0        434          920         162       2001   
3         216           0        540          756           0       1915   
4         655           0        490         1145         350       2000   

   YearRemodAdd  OverallQual  OverallCond  LotArea  LotFrontage  MoSold  \
0          2003            7            5     8450           65       2   
1          1976            6            8     9600           80       5   
2          2002            7            5    11250           68       9   
3          1970            7            5     9550           60       2   
4          2000            8            5    14260           84      12   

   YrSold  PoolQC_Ex  PoolQC_Gd  Fence_GdPrv  Fence_GdWo  Fence_MnPrv  \
0    2008          0          1            0           0            1   
1    2007          0          1            0           0            1   
2    2008          0          1            0           0            1   
3    2006          0          1            0           0            1   
4    2008          0          1            0           0            1   

   Fence_MnWw  MiscFeature_Gar2  MiscFeature_Othr  MiscFeature_Shed  \
0           0                 0                 0                 1   
1           0                 0                 0                 1   
2           0                 0                 0                 1   
3           0                 0                 0                 1   
4           0                 0                 0                 1   

   GarageType_2Types  GarageType_Attchd  GarageType_Basment  \
0                  0                  1                   0   
1                  0                  1                   0   
2                  0                  1                   0   
3                  0                  0                   0   
4                  0                  1                   0   

   GarageType_BuiltIn  GarageType_

In [10]:
x=dummytrain1.drop("SalePrice",axis=1)
y=dummytrain1.SalePrice

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_train = pd.DataFrame(sc.fit_transform(dummytrain1), columns=dummytrain1.columns)
scaled_train.head()




MSSubClass  ScreenPorch  PoolArea   MiscVal  GarageYrBlt  GarageCars  \
0    0.073375    -0.270208 -0.068692 -0.087688     1.017598    0.311725   
1   -0.872563    -0.270208 -0.068692 -0.087688    -0.107927    0.311725   
2    0.073375    -0.270208 -0.068692 -0.087688     0.934226    0.311725   
3    0.309859    -0.270208 -0.068692 -0.087688     0.809167    1.650307   
4    0.073375    -0.270208 -0.068692 -0.087688     0.892540    1.650307   

   GarageArea  WoodDeckSF  OpenPorchSF  EnclosedPorch  X3SsnPorch  \
0    0.351000   -0.752176     0.216503      -0.359325   -0.116339   
1   -0.060731    1.626195    -0.704483      -0.359325   -0.116339   
2    0.631726   -0.752176    -0.070361      -0.359325   -0.116339   
3    0.790804   -0.752176    -0.176048       4.092524   -0.116339   
4    1.698485    0.780197     0.563760      -0.359325   -0.116339   

   BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0      1.107810     -0.241061  0.789741  1.227585      0.163779     -0.211454   
1     -0.819964      3.948809  0.789741 -0.761621      0.163779     -0.211454   
2      1.107810     -0.241061  0.789741  1.227585      0.163779     -0.211454   
3      1.107810     -0.241061 -1.026041 -0.761621      0.163779     -0.211454   
4      1.107810     -0.241061  0.789741  1.227585      1.390023     -0.211454   

   TotRmsAbvGrd  Fireplaces  X1stFlrSF  X2ndFlrSF  LowQualFinSF  GrLivArea  \
0      0.912210   -0.951226  -0.793434   1.161852     -0.120242   0.370333   
1     -0.318683    0.600495   0.257140  -0.795163     -0.120242  -0.482512   
2     -0.318683    0.600495  -0.627826   1.189351     -0.120242   0.515013   
3      0.296763    0.600495  -0.521734   0.937276     -0.120242   0.383659   
4      1.527656    0.600495  -0.045611   1.617877     -0.120242   1.299326   

   BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  MasVnrArea  YearBuilt  \
0    0.575425   -0.288653  -0.944591    -0.459303    0.514104   1.050994   
1    1.171992   -0.288653  -0.641228     0.466465   -0.570750   0.156734   
2    0.092907   -0.288653  -0.301643    -0.313369    0.325915   0.984752   
3   -0.499274   -0.288653  -0.061670    -0.687324   -0.570750  -1.863632   
4    0.463568   -0.288653  -0.174865     0.199680    1.366489   0.951632   

   YearRemodAdd  OverallQual  OverallCond   LotArea  LotFrontage    MoSold  \
0      0.878668     0.651479    -0.517200 -0.207142    -0.220875 -1.599111   
1     -0.429577    -0.071836     2.179628 -0.091886     0.460320 -0.489110   
2      0.830215     0.651479    -0.517200  0.073480    -0.084636  0.990891   
3     -0.720298     0.651479    -0.517200 -0.096897    -0.447940 -1.599111   
4      0.733308     1.374795    -0.517200  0.375148     0.641972  2.100892   

     YrSold  PoolQC_Ex  PoolQC_Gd  Fence_GdPrv  Fence_GdWo  Fence_MnPrv  \
0  0.138777  -0.037037   0.052414    -0.205214   -0.195977     0.304655   
1 -0.614439  -0.037037   0.052414    -0.205214   -0.195977     0.304655   
2  0.138777  -0.037037   0.052414    -0.205214   -0.195977     0.304655   
3 -1.367655  -0.037037   0.052414    -0.205214   -0.195977     0.304655   
4  0.138777  -0.037037   0.052414    -0.205214   -0.195977     0.304655   

   Fence_MnWw  MiscFeature_Gar2  MiscFeature_Othr  MiscFeature_Shed  \
0   -0.087129         -0.037037         -0.037037          0.058621   
1   -0.087129         -0.037037         -0.037037          0.058621   
2   -0.087129         -0.037037         -0.037037          0.058621   
3   -0.087129         -0.037037         -0.037037          0.058621   
4   -0.087129         -0.037037         -0.037037          0.058621   

   GarageType_2Types  GarageType_Attchd  GarageType_Basment  \
0          -0.064238           0.731591           -0.114827   
1          -0.064238           0.731591           -0.114827   
2          -0.064238           0.731591           -0.114827   
3          -0.064238          -1.366883           -0.114827   
4          -0.064238           0.731591           -0.114827   

In [12]:
scaled_test = pd.DataFrame(sc.fit_transform(dummytest), columns=dummytest.columns)
scaled_test.head()

MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  YearBuilt  \
0   -0.874711     0.567330  0.363929    -0.751101     0.400766  -0.340945   
1   -0.874711     0.615963  0.897861    -0.054877     0.400766  -0.439695   
2    0.061351     0.275532  0.809646    -0.751101    -0.497418   0.844059   
3    0.061351     0.470064  0.032064    -0.054877     0.400766   0.876976   
4    1.465443    -1.232092 -0.971808     1.337571    -0.497418   0.679475   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0     -1.072885   -0.563316    0.063428    0.517537  -0.650461    -0.370716   
1     -1.214908    0.047057    1.063511   -0.297689  -0.339225     0.639230   
2      0.678742   -0.563316    0.773377   -0.297689  -0.954831    -0.266784   
3      0.678742   -0.450284    0.357958   -0.297689  -0.526882    -0.271303   
4      0.394694   -0.563316   -0.387160   -0.297689   1.059048     0.528520   

   X1stFlrSF  X2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
0  -0.654561  -0.775254     -0.080483  -1.215588     -0.818068      -0.25816   
1   0.433298  -0.775254     -0.080483  -0.323539     -0.818068      -0.25816   
2  -0.574165   0.891944     -0.080483   0.294508     -0.818068      -0.25816   
3  -0.579190   0.837243     -0.080483   0.243004     -0.818068      -0.25816   
4   0.310192  -0.775254     -0.080483  -0.424487     -0.818068      -0.25816   

   FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  \
0 -1.028720 -0.751040     -1.029543      -0.20391     -0.918335   -0.898055   
1 -1.028720  1.237648      0.175997      -0.20391     -0.255371   -0.898055   
2  0.773083  1.237648      0.175997      -0.20391     -0.255371    0.647066   
3  0.773083  1.237648      0.175997      -0.20391      0.407593    0.647066   
4  0.773083 -0.751040     -1.029543      -0.20391     -0.918335   -0.898055   

   GarageYrBlt  GarageCars  GarageArea  WoodDeckSF  OpenPorchSF  \
0    -0.653107   -0.988189    1.185921    0.366678    -0.701628   
1    -0.769806   -0.988189   -0.741235    2.347867    -0.178826   
2     0.747276    0.301406    0.042537    0.930495    -0.207871   
3     0.786176    0.301406   -0.012788    2.089451    -0.178826   
4     0.552779    0.301406    0.153187   -0.729632     0.489198   

   EnclosedPorch  X3SsnPorch  ScreenPorch  PoolArea    MiscVal    MoSold  \
0      -0.360738   -0.088827     1.818960 -0.057227  -0.092244 -0.038281   
1      -0.360738   -0.088827    -0.301543 -0.057227  19.730438 -0.038281   
2      -0.360738   -0.088827    -0.301543 -0.057227  -0.092244 -1.140614   
3      -0.360738   -0.088827    -0.301543 -0.057227  -0.092244 -0.038281   
4      -0.360738   -0.088827     2.243060 -0.057227  -0.092244 -1.875504   

     YrSold  MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  \
0  1.713905         -0.101921    -0.231148    12.037442    -1.810688   
1  1.713905         -0.101921    -0.231148    -0.083074     0.552276   
2  1.713905         -0.101921    -0.231148    -0.083074     0.552276   
3  1.713905         -0.101921    -0.231148    -0.083074     0.552276   
4  1.713905         -0.101921    -0.231148    -0.083074     0.552276   

   MSZoning_RM  Street_Grvl  Street_Pave  Alley_Grvl  Alley_Pave  \
0    -0.445926     -0.06426      0.06426    0.161306   -0.161306   
1    -0.445926     -0.06426      0.06426    0.161306   -0.161306   
2    -0.445926     -0.06426      0.06426    0.161306   -0.161306   
3    -0.445926     -0.06426      0.06426    0.161306   -0.161306   
4    -0.445926     -0.06426      0.06426    0.161306   -0.161306   

   LotShape_IR1  LotShape_IR2  LotShape_IR3  LotShape_Reg  LandContour_Bnk  \
0     -0.704564     -0.156776      -0.06426      0.749732        -0.196046   
1      1.419318     -0.156776      -0.06426     -1.333809        -0.196046   
2      1.419318     -0.156776      -0.06426     -1.333809        -0.196046   
3      1.419318     -0.156776      -0.06426     -1.333809        -0.196046   
4      1.419318  

In [13]:
x=scaled_train.drop("SalePrice",axis=1)
y=scaled_train.SalePrice

In [14]:
from sklearn.linear_model import LinearRegression
Devil = LinearRegression()



In [52]:
Devil.fit(pd.DataFrame(x),y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
pred1=Devil.predict(scaled_test)


In [54]:
pred1

array([-3.27625695e+11,  1.74315149e+12, -2.25083834e+11, ...,
       -5.49931309e+09, -9.81216289e+11,  1.44747709e+11])

In [23]:
newHprice = sc.fit_transform(pd.DataFrame(train.SalePrice))

In [56]:
hprice = sc.inverse_transform(pred1)

In [57]:
hprice

array([-2.60184902e+16,  1.38432884e+17, -1.78750984e+16, ...,
       -4.36729554e+14, -7.79235780e+16,  1.14951816e+16])

In [58]:
solution = pd.DataFrame({"Id":test.Id, "SalePrice":hprice})

In [59]:
solution.to_csv("my_LR Model.csv", index = False)

In [60]:
cd

C:\Users\Asus


# Random Forest

In [61]:
from sklearn.ensemble import RandomForestRegressor


In [62]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)


In [63]:
rf.fit(pd.DataFrame(x),y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1000,
                      n_jobs=None, oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [64]:
pred2=rf.predict(scaled_test)


In [65]:
hprice = sc.inverse_transform(pred2)
hprice

array([141911.41      , 136889.4375    , 166042.94333333, ...,
       176758.579     , 144708.474     , 203102.354     ])

In [31]:
solution = pd.DataFrame({"Id":test.Id, "SalePrice":hprice})

In [32]:
solution.to_csv("my_RF Model.csv", index = False)

# Decision Tree

In [33]:
from sklearn.tree import DecisionTreeRegressor

In [34]:
baby = DecisionTreeRegressor()

In [35]:
baby.fit(pd.DataFrame(x),y)
pred3=baby.predict(scaled_test)
pred3


array([-0.44602488, -0.52787309,  0.3787533 , ..., -0.14381608,
       -0.39565674,  0.78169837])

In [36]:
hprice = sc.inverse_transform(pred3)
hprice

array([145500., 139000., 211000., ..., 169500., 149500., 243000.])

In [37]:
solution = pd.DataFrame({"Id":test.Id, "SalePrice":hprice})

In [38]:
solution.to_csv("my_DT Model.csv", index = False)

# Ridge Regression

In [49]:
from sklearn.linear_model import Ridge


In [50]:
baby1 =Ridge()

In [52]:
baby1.fit(pd.DataFrame(x),y)


Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [53]:
pred4=baby1.predict(scaled_test)


In [54]:
pred4

array([-0.6235176 , -1.2696097 ,  0.12122549, ...,  0.03445024,
        0.17856549,  1.10954448])

In [59]:
hprice = sc.inverse_transform(pred4)
hprice

array([131404.3640264 ,  80094.77068754, 190548.35344277, ...,
       183657.07155441, 195102.0262503 , 269035.99464478])

In [60]:
solution = pd.DataFrame({"Id":test.Id, "SalePrice":hprice})

In [61]:
solution.to_csv("my_Ridge Model.csv", index = False)

# Lasso Regression

In [47]:
from sklearn.linear_model import Lasso


In [48]:
baby2 =Lasso()

In [49]:
baby2.fit(pd.DataFrame(x),y)


Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [50]:
pred5=baby2.predict(scaled_test)


In [51]:
hprice = sc.inverse_transform(pred5)
hprice

ValueError: operands could not be broadcast together with shapes (1459,) (270,) (1459,) 

In [87]:
solution = pd.DataFrame({"Id":test.Id, "SalePrice":hprice})

In [88]:
solution.to_csv("my_Lasso Model.csv", index = False)

# XGBOOST

In [19]:
from xgboost.sklearn import XGBRegressor


In [20]:
REAL_DEVIL=XGBRegressor()

In [ ]:
x.sort_index(axis=1,inplace=True)


In [ ]:
scaled_test.sort_index(axis=1,inplace=True)


In [21]:
REAL_DEVIL.fit(pd.DataFrame(x),y)


C:\Users\Asus\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
C:\Users\Asus\Anaconda3\lib\site-packages\xgboost\core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[04:34:15] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [22]:
pred6=REAL_DEVIL.predict(scaled_test)
pred6


array([-0.6665232 , -0.23149687,  0.03658518, ..., -0.25134993,
       -0.72431326,  0.8179377 ], dtype=float32)

In [24]:
hprice = sc.inverse_transform(pred6)
hprice

array([127989.06, 162536.81, 183826.62, ..., 160960.17, 123399.65,
       245877.95], dtype=float32)

In [25]:
solution = pd.DataFrame({"Id":test.Id, "SalePrice":hprice})

In [26]:
solution.to_csv("my_XGBoost Model.csv", index = False)