In [3]:
import pandas as pd
import numpy as np

In [44]:
data=pd.read_csv("G:\\Datasets\\UpVotes\\train_upvotes.csv")
test=pd.read_csv("G:\\Datasets\\UpVotes\\test_upvotes.csv")

In [5]:
data.head()

ID Tag  Reputation  Answers  Username    Views  Upvotes
0   52664   a      3942.0      2.0    155623   7855.0     42.0
1  327662   a     26046.0     12.0     21781  55801.0   1175.0
2  468453   c      1358.0      4.0     56177   8067.0     60.0
3   96996   a       264.0      3.0    168793  27064.0      9.0
4  131465   c      4271.0      4.0    112223  13986.0     83.0

In [6]:
data.isnull().sum()

ID            0
Tag           0
Reputation    0
Answers       0
Username      0
Views         0
Upvotes       0
dtype: int64

In [7]:
data.Tag.unique()

array(['a', 'c', 'r', 'j', 'p', 's', 'h', 'o', 'i', 'x'], dtype=object)

In [8]:
z=pd.get_dummies(data["Tag"])
z.head()


a  c  h  i  j  o  p  r  s  x
0  1  0  0  0  0  0  0  0  0  0
1  1  0  0  0  0  0  0  0  0  0
2  0  1  0  0  0  0  0  0  0  0
3  1  0  0  0  0  0  0  0  0  0
4  0  1  0  0  0  0  0  0  0  0

In [9]:
data1=pd.concat([data, z],axis=1)


In [10]:
data=data1.drop(["Tag","ID"],axis=1)

In [11]:
data.head()

Reputation  Answers  Username    Views  Upvotes  a  c  h  i  j  o  p  r  s  \
0      3942.0      2.0    155623   7855.0     42.0  1  0  0  0  0  0  0  0  0   
1     26046.0     12.0     21781  55801.0   1175.0  1  0  0  0  0  0  0  0  0   
2      1358.0      4.0     56177   8067.0     60.0  0  1  0  0  0  0  0  0  0   
3       264.0      3.0    168793  27064.0      9.0  1  0  0  0  0  0  0  0  0   
4      4271.0      4.0    112223  13986.0     83.0  0  1  0  0  0  0  0  0  0   

   x  
0  0  
1  0  
2  0  
3  0  
4  0

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_train = pd.DataFrame(sc.fit_transform(data), columns=data.columns)
scaled_train.head()


Reputation   Answers  Username     Views   Upvotes         a         c  \
0   -0.141573 -0.535736  1.507266 -0.269158 -0.082258  3.068087 -0.530373   
1    0.675238  2.257943 -1.212270  0.323087  0.233127  3.068087 -0.530373   
2   -0.237059  0.023000 -0.513378 -0.266540 -0.077247 -0.325936  1.885466   
3   -0.277486 -0.256368  1.774867 -0.031882 -0.091444  3.068087 -0.530373   
4   -0.129415  0.023000  0.625421 -0.193426 -0.070845 -0.325936  1.885466   

          h         i         j        o         p         r         s  \
0 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
1 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
2 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
3 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
4 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   

          x  
0 -0.146967  
1 -0.146967  
2 -0.146967  
3 -0.146967  
4 -0.146967

In [13]:
from sklearn.model_selection import train_test_split
y=scaled_train["Upvotes"]
x=scaled_train.drop(["Upvotes"],axis=1)


In [14]:
from sklearn.linear_model import LinearRegression
Baby=LinearRegression()

In [15]:
Baby.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
test.head()

ID Tag  Reputation  Answers  Username    Views
0  366953   a      5645.0      3.0     50652  33200.0
1   71864   c     24511.0      6.0     37685   2730.0
2  141692   i       927.0      1.0    135293  21167.0
3  316833   i        21.0      6.0    166998  18528.0
4  440445   i      4475.0     10.0     53504  57240.0

In [17]:
t=pd.get_dummies(test["Tag"])
t.head()


a  c  h  i  j  o  p  r  s  x
0  1  0  0  0  0  0  0  0  0  0
1  0  1  0  0  0  0  0  0  0  0
2  0  0  0  1  0  0  0  0  0  0
3  0  0  0  1  0  0  0  0  0  0
4  0  0  0  1  0  0  0  0  0  0

In [18]:
test1=pd.concat([test, t],axis=1)


In [19]:
test=test1.drop(["Tag","ID"],axis=1)
test.head()

Reputation  Answers  Username    Views  a  c  h  i  j  o  p  r  s  x
0      5645.0      3.0     50652  33200.0  1  0  0  0  0  0  0  0  0  0
1     24511.0      6.0     37685   2730.0  0  1  0  0  0  0  0  0  0  0
2       927.0      1.0    135293  21167.0  0  0  0  1  0  0  0  0  0  0
3        21.0      6.0    166998  18528.0  0  0  0  1  0  0  0  0  0  0
4      4475.0     10.0     53504  57240.0  0  0  0  1  0  0  0  0  0  0

In [20]:
scaled_test = pd.DataFrame(sc.fit_transform(test), columns=test.columns)
scaled_test.head()


Reputation   Answers  Username     Views         a         c         h  \
0   -0.081543 -0.255734 -0.625867  0.041742  3.071288 -0.527522 -0.257286   
1    0.594400  0.582853 -0.890252 -0.337505 -0.325596  1.895656 -0.257286   
2   -0.250583 -0.814791  1.099883 -0.108028 -0.325596 -0.527522 -0.257286   
3   -0.283044  0.582853  1.746318 -0.140874 -0.325596 -0.527522 -0.257286   
4   -0.123463  1.700969 -0.567718  0.340957 -0.325596 -0.527522 -0.257286   

          i         j         o        p         r         s         x  
0 -0.332746 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
1 -0.332746 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
2  3.005291 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
3  3.005291 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
4  3.005291 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053

In [21]:
pred=Baby.predict(scaled_test)

In [22]:
pred

array([ 1.01429155e+09,  3.04997385e+09, -6.06807312e+09, ...,
       -2.08297515e+09, -4.13363540e+09,  1.01429155e+09])

In [39]:
newHprice = sc.fit_transform(pd.DataFrame(data.Upvotes))

In [24]:
pred=sc.inverse_transform(pred)

In [25]:
pred

array([ 3.64377717e+12,  1.09568349e+13, -2.17991625e+13, ...,
       -7.48295429e+12, -1.48498194e+13,  3.64377717e+12])

In [26]:
solution = pd.DataFrame({"ID":test1.ID, "Upvotes":pred})
solution.to_csv("Upvotes_LR Model.csv", index = False)

In [27]:
solution.head()

ID       Upvotes
0  366953  3.643777e+12
1   71864  1.095683e+13
2  141692 -2.179916e+13
3  316833 -2.179916e+13
4  440445 -2.179916e+13

In [28]:
pred=Baby.fit(data.drop("Upvotes",axis=1),data.Upvotes).predict(test)

In [29]:
solution = pd.DataFrame({"ID":test1.ID, "Upvotes":pred})
solution.to_csv("Upvotes_LR Model.csv", index = False)

In [30]:
# XGBoost

In [31]:
from xgboost.sklearn import XGBRegressor
REAL_DEVIL=XGBRegressor()
REAL_DEVIL.fit(data.drop("Upvotes",axis=1),data.Upvotes)


C:\Users\Asus\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
C:\Users\Asus\Anaconda3\lib\site-packages\xgboost\core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[11:28:35] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [32]:
pred=REAL_DEVIL.predict(test)
pred

array([172.30612 , 357.21378 ,  59.15491 , ..., 164.33508 ,  -8.984699,
        13.860401], dtype=float32)

In [33]:
solution = pd.DataFrame({"ID":test1.ID, "Upvotes":pred})
solution.to_csv("Upvotes_XGBoost Model.csv", index = False)

In [34]:
########

In [35]:
data.head()

Reputation  Answers  Username    Views  Upvotes  a  c  h  i  j  o  p  r  s  \
0      3942.0      2.0    155623   7855.0     42.0  1  0  0  0  0  0  0  0  0   
1     26046.0     12.0     21781  55801.0   1175.0  1  0  0  0  0  0  0  0  0   
2      1358.0      4.0     56177   8067.0     60.0  0  1  0  0  0  0  0  0  0   
3       264.0      3.0    168793  27064.0      9.0  1  0  0  0  0  0  0  0  0   
4      4271.0      4.0    112223  13986.0     83.0  0  1  0  0  0  0  0  0  0   

   x  
0  0  
1  0  
2  0  
3  0  
4  0

In [36]:
scaled_train = pd.DataFrame(sc.fit_transform(data), columns=data.columns)
scaled_train.head()

Reputation   Answers  Username     Views   Upvotes         a         c  \
0   -0.141573 -0.535736  1.507266 -0.269158 -0.082258  3.068087 -0.530373   
1    0.675238  2.257943 -1.212270  0.323087  0.233127  3.068087 -0.530373   
2   -0.237059  0.023000 -0.513378 -0.266540 -0.077247 -0.325936  1.885466   
3   -0.277486 -0.256368  1.774867 -0.031882 -0.091444  3.068087 -0.530373   
4   -0.129415  0.023000  0.625421 -0.193426 -0.070845 -0.325936  1.885466   

          h         i         j        o         p         r         s  \
0 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
1 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
2 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
3 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   
4 -0.257773 -0.329931 -0.529313 -0.21472 -0.389146 -0.197926 -0.275753   

          x  
0 -0.146967  
1 -0.146967  
2 -0.146967  
3 -0.146967  
4 -0.146967

In [37]:
scaled_test = pd.DataFrame(sc.fit_transform(test), columns=test.columns)
scaled_test.head()

Reputation   Answers  Username     Views         a         c         h  \
0   -0.081543 -0.255734 -0.625867  0.041742  3.071288 -0.527522 -0.257286   
1    0.594400  0.582853 -0.890252 -0.337505 -0.325596  1.895656 -0.257286   
2   -0.250583 -0.814791  1.099883 -0.108028 -0.325596 -0.527522 -0.257286   
3   -0.283044  0.582853  1.746318 -0.140874 -0.325596 -0.527522 -0.257286   
4   -0.123463  1.700969 -0.567718  0.340957 -0.325596 -0.527522 -0.257286   

          i         j         o        p         r         s         x  
0 -0.332746 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
1 -0.332746 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
2  3.005291 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
3  3.005291 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053  
4  3.005291 -0.527719 -0.215835 -0.39047 -0.197554 -0.277122 -0.147053

In [38]:
pred_scaled=REAL_DEVIL.predict(scaled_test)
pred_scaled

array([-52.47165, -41.60277, -52.47165, ..., -52.47165, -52.47165,
       -52.47165], dtype=float32)

In [40]:
pred_sclaed=sc.inverse_transform(pred_scaled)

In [45]:
solution = pd.DataFrame({"ID":test.ID, "Upvotes":pred_scaled})
solution.to_csv("Upvotes_XGBoost Model.csv", index = False)

In [43]:
test.head()

Reputation  Answers  Username    Views  a  c  h  i  j  o  p  r  s  x
0      5645.0      3.0     50652  33200.0  1  0  0  0  0  0  0  0  0  0
1     24511.0      6.0     37685   2730.0  0  1  0  0  0  0  0  0  0  0
2       927.0      1.0    135293  21167.0  0  0  0  1  0  0  0  0  0  0
3        21.0      6.0    166998  18528.0  0  0  0  1  0  0  0  0  0  0
4      4475.0     10.0     53504  57240.0  0  0  0  1  0  0  0  0  0  0