# question - 01


Create an empty array of 20 0's and replace the 6th object with the number 5.


CODING/OUTPUT FORMAT:

Step 1:- Create an empty array with 20 zeros

Step 2:- Replace the sixth object with number 5

Step 3:- Print the array

In [1]:
#Calling Libraries.

import numpy as np


#Write a code to retrive the empty array with 20 zeros.

arr=np.zeros(20)


#write a code replace the sixth object with number 5.

arr[5]=5


# write a code to print the array.

print(arr)


[0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# question - 2


Create an array containing 30 1's and Replace all the one's with 100.


CODING/OUTPUT FORMAT:

Step 1:- Create an empty array with 30 ones.

Step 2:- Replace all the numbers in the array with number 100.

Step 3:- Print the array.

In [2]:
# calling library.

import numpy as np

# Write a code to retrive the empty array with 30 one's.

arr = np.ones(30)

# Write a code replace all the values in the aray with number 100 .

arr[:]=100

#write a code to print the array.

print(arr)

[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100.]


# question - 3

Create an array of integers starting from 21 until 31 (both included) and name it as array1 and create an array of
integers starting from 11 until 21 (both included) and name it as array2. Calculate the difference between array1 and
array2.




CODING/OUTPUT FORMAT:



Step 1:- Create an array of integers begins with 21 upto 31 and name/assign it to array1 .

Step 2:- Create an array of integers begins with 11 upto 21 and name/assign it to array2 .

Step 3:- Calculate the difference between array1 and array2.

Step 4:- Print the array.

In [3]:
#calling library
import numpy as np



# Write a code to create an array of integers starts with 21 and upto 31 and name/assign it to array1.


array1= np.arange(21,32)


# Write a code to create an array of integers starts with 11 and upto 22 and name/assign it to array2.

array2= np.arange(11,22)

# Write a code to retrive the difference between array1 and array2 and assign/name it to array3.

array3=array1-array2

#Write a code to print the array3.

print(array3)


[10 10 10 10 10 10 10 10 10 10 10]


# question - 4

Create an array of all even integers from 2 to 10 (both included) and name/assign it to a1 and create an array of all even integers from 22 to 30 (both included) and name/assign it to a2 ,Use the 2 arrays as rows(first row as a1, second row as a2) and create a matrix
[ Hint - Use stack function from numpy ].


CODING/OUTPUT FORMAT:



Step 1:- Create an array of all even integers begins with 2 upto 10 and name/assign it to a1 .

Step 2:- Create an array of all even integers begins with 22 upto 30 and name/assign it to a2 .

Step 3:- Create a matrix from the above two arrays rows and name/assign it to a3 .[use stack function from numpy]

Step 4:- Print the matrix a3.



In [4]:
#calling library
import numpy as np

#write a code to Create an array of all even integers begins with 2 upto 10 and name/assign it to a1.

a1=np.arange(2,11,2)

#write a code to Create an array of all even integers begins with 22 upto 30 and name/assign it to a2 .
a2 = np.arange(22,31,2)

#write a code to Create a matrix from the above two arrays rows and name/assign it to a3 .[use stack function from numpy]
a3=np.stack((a1,a2))

#write a code to the print the matrix a3.

print(a3)

[[ 2  4  6  8 10]
 [22 24 26 28 30]]


# question - 5
Create a 5x6 matrix with values ranging from 0 to 29 (both included) and retrieve the value intersecting at 2nd row and 3rd column.


CODING/OUTPUT FORMAT:



Step 1:- Create an 5x6 matrix the values ranging from 0 to 29 (both included).

Step 2:- Print the value intersecting at 2nd row and 3rd column.

In [5]:
#calling libraries
import numpy as np

# Write a code to Create an 5x6 matrix the values ranging from 0 to 29 .[use arange,reshape]

arr_matrix=np.arange(30).reshape(5,6)

# Write a code to print the value that intersecting the 2nd row and 3rd column.

print(arr_matrix[1,2])

8


# QUESTION - 6

Create an identity matrix of shape 5x5 and replace the 0's with the value 21


CODING/OUTPUT FORMAT:



Step 1:- Create an 5x5 identity matrix .

Step 2:- Replace all the 0's with the value 21.

Step 3 : Print the matrix.

In [6]:
#calling libraries

import numpy as np

# Write a code to Create an 5x5 identity matrix .[use eye/identity from numpy library]

arr=np.eye(5)

# Write a code to Create to replace all the 0's with the value 21.

arr[arr == 0] = 21

# Write a code to print the matrix.

print(arr)


[[ 1. 21. 21. 21. 21.]
 [21.  1. 21. 21. 21.]
 [21. 21.  1. 21. 21.]
 [21. 21. 21.  1. 21.]
 [21. 21. 21. 21.  1.]]


# QUESTION - 7
Create an array of 30 linearly spaced points between 0 to 100 (both included):


CODING/OUTPUT FORMAT:



Step 1:- Create an array with an 30 linearly spaced points between 0 and 100. Hint:[Use linspace from Numpy Library]

Step 2:- print the array.

In [7]:
#calling library

import numpy as np

# Write a code to create an array ranging from 0 to 100 with 30 linearly spaced point [USE linspace from Numpy Library]

arr=np.linspace(0,100,30)

# Write a code to print the array.

print(arr)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


# QUESTIONS - 8

Using the below given Matrix, generate the output for the below questions.


array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

 [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

 [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

 [ 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],

 [ 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],

 [ 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],

 [ 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],

 [ 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],

 [ 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],

 [ 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])



Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique.


CODING/OUTPUT FORMAT:-



Step 1 : View the above matrix and write a code to print the last 2 rows and first 3 columns.

In [8]:
# Calling libraries

import numpy as np

# The below code generate the values ranging from 1 to 100 and create a 10x10 matrix.

matrix = np.arange(1,101).reshape(10,10)

# write a code to print the last 2 rows and first 3 columns.

print(matrix[8:,0:3])

[[81 82 83]
 [91 92 93]]


# QUESTION - 9

Using the below given Matrix, generate the output for the below questions.


array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

 [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

 [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

 [ 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],

 [ 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],

 [ 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],

 [ 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],

 [ 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],

 [ 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],

 [ 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])



 Retrieve the value 55 from the above matrix using index & selection technique.


CODING/OUTPUT FORMAT:-



Step 1 :- View the above matrix and write a code to print the value 55 from the above matrix using index & selection technique.

In [9]:
# Calling libraries

import numpy as np

# The below code generate the values ranging from 1 to 100 and create a 10x10 matrix.

matrix = np.arange(1,101).reshape(10,10)


# Write a code to print the value 55 using index and selection technique.

print(matrix[5,4])

55


# QUESTION- 10
Using the below given Matrix, generate the output for the below questions.


array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

 [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

 [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

 [ 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],

 [ 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],

 [ 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],

 [ 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],

 [ 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],

 [ 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],

 [ 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])



Retrieve all the values from the 3rd column in the above matrix


CODING/OUTPUT FORMAT:-



Step 1 :- View the above matrix and write a code to print all the values from 3rd column.



In [10]:
# Calling libraries

import numpy as np

# The below code generate the values ranging from 1 to 100 and create a 10x10 matrix.

matrix = np.arange(1,101).reshape(10,10)


# Write a code to print the values from 3rd column,using index and selection technique.

print(matrix[:,2])

[ 3 13 23 33 43 53 63 73 83 93]


# QUESTION - 11

Using the below given Matrix, generate the output for the below questions.


array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

 [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

 [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

 [ 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],

 [ 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],

 [ 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],

 [ 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],

 [ 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],

 [ 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],

 [ 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])



Retrieve the values from the 4th row in the above matrix


CODING/OUTPUT FORMAT:-



Step 1 :- View the above matrix and write a code to print the values from fourth row.



In [11]:
# Calling libraries

import numpy as np

# The below code generate the values ranging from 1 to 100 and create a 10x10 matrix.

matrix = np.arange(1,101).reshape(10,10)


# Write a code to print the values from fourth row.,using index and selection technique.

print(matrix[3,:])

[31 32 33 34 35 36 37 38 39 40]


# QUESTION - 12
Using the below given Matrix, generate the output for the below questions.


array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

 [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

 [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

 [ 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],

 [ 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],

 [ 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],

 [ 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],

 [ 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],

 [ 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],

 [ 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])



Retrieve all the values from the 2nd & 4th rows in the above matrix.


CODING/OUTPUT FORMAT:-



Step 1 :- View the above matrix and write a code to print the second and fourth row of the matrix above.

In [12]:
# Calling libraries

import numpy as np

# The below code generate the values ranging from 1 to 100 and create a 10x10 matrix.

matrix = np.arange(1,101).reshape(10,10)


# write a code to print the values from second and fourth row,using index and selection technique.

print(matrix[(1,3),:])


[[11 12 13 14 15 16 17 18 19 20]
 [31 32 33 34 35 36 37 38 39 40]]


# QUESTION - 13

Using the below given Matrix, generate the output for the below questions.


array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

 [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

 [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

 [ 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],

 [ 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],

 [ 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],

 [ 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],

 [ 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],

 [ 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],

 [ 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])



Calculate sum of all the values in the matrix.


CODING/OUTPUT FORMAT:-



Step 1 :- View the above matrix and write a code to print the total sum of all the values in the matrix.

In [13]:
# Calling libraries

import numpy as np

# The below code generate the values ranging from 1 to 100 and create a 10x10 matrix.

matrix = np.arange(1,101).reshape(10,10)


# write a code to print the sum of all the values in the matrix.

print(matrix.sum())

5050
